//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonInfoHelperWinform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonInfoHelperWinform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;-none-&quot;: {
        ///    &quot;normal&quot;: 1,
        ///    &quot;fire&quot;: 1,
        ///    &quot;water&quot;: 1,
        ///    &quot;electric&quot;: 1,
        ///    &quot;grass&quot;: 1,
        ///    &quot;ice&quot;: 1,
        ///    &quot;fighting&quot;: 1,
        ///    &quot;poison&quot;: 1,
        ///    &quot;ground&quot;: 1,
        ///    &quot;flying&quot;: 1,
        ///    &quot;psychic&quot;: 1,
        ///    &quot;bug&quot;: 1,
        ///    &quot;rock&quot;: 1,
        ///    &quot;ghost&quot;: 1,
        ///    &quot;dragon&quot;: 1,
        ///    &quot;dark&quot;: 1,
        ///    &quot;steel&quot;: 1
        ///  },
        ///  &quot;normal&quot;: {
        ///    &quot;normal&quot;: 1,
        ///    &quot;fire&quot;: 1,
        ///    &quot;water&quot;: 1,
        ///    &quot;electric&quot;: 1,
        ///    &quot;grass&quot;: 1,
        ///    &quot;ice&quot;: 1,
        ///    &quot;fighting&quot;: 1,
        ///    &quot;poison&quot;: 1,
        ///    &quot;ground&quot;: 1,
        ///    &quot;flying&quot;: 1,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttackingPokemonTypesGen2 {
            get {
                return ResourceManager.GetString("AttackingPokemonTypesGen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;-none-&quot;: {
        ///    &quot;normal&quot;: 1,
        ///    &quot;fire&quot;: 1,
        ///    &quot;water&quot;: 1,
        ///    &quot;electric&quot;: 1,
        ///    &quot;grass&quot;: 1,
        ///    &quot;ice&quot;: 1,
        ///    &quot;fighting&quot;: 1,
        ///    &quot;poison&quot;: 1,
        ///    &quot;ground&quot;: 1,
        ///    &quot;flying&quot;: 1,
        ///    &quot;psychic&quot;: 1,
        ///    &quot;bug&quot;: 1,
        ///    &quot;rock&quot;: 1,
        ///    &quot;ghost&quot;: 1,
        ///    &quot;dragon&quot;: 1,
        ///    &quot;dark&quot;: 1,
        ///    &quot;steel&quot;: 1,
        ///    &quot;fairy&quot;: 1
        ///  },
        ///  &quot;normal&quot;: {
        ///    &quot;normal&quot;: 1,
        ///    &quot;fire&quot;: 1,
        ///    &quot;water&quot;: 1,
        ///    &quot;electric&quot;: 1,
        ///    &quot;grass&quot;: 1,
        ///    &quot;ice&quot;: 1,
        ///    &quot;fighting&quot;: 1,
        ///    &quot;poison&quot;: 1,
        ///    &quot;ground&quot;: 1,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttackingPokemonTypesGen6 {
            get {
                return ResourceManager.GetString("AttackingPokemonTypesGen6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;-none-&quot;: {
        ///    &quot;normal&quot;: 1,
        ///    &quot;fire&quot;: 1,
        ///    &quot;water&quot;: 1,
        ///    &quot;electric&quot;: 1,
        ///    &quot;grass&quot;: 1,
        ///    &quot;ice&quot;: 1,
        ///    &quot;fighting&quot;: 1,
        ///    &quot;poison&quot;: 1,
        ///    &quot;ground&quot;: 1,
        ///    &quot;flying&quot;: 1,
        ///    &quot;psychic&quot;: 1,
        ///    &quot;bug&quot;: 1,
        ///    &quot;rock&quot;: 1,
        ///    &quot;ghost&quot;: 1,
        ///    &quot;dragon&quot;: 1,
        ///    &quot;dark&quot;: 1,
        ///    &quot;steel&quot;: 1
        ///  },
        ///  &quot;normal&quot;: {
        ///    &quot;normal&quot;: 1,
        ///    &quot;fire&quot;: 1,
        ///    &quot;water&quot;: 1,
        ///    &quot;electric&quot;: 1,
        ///    &quot;grass&quot;: 1,
        ///    &quot;ice&quot;: 1,
        ///    &quot;fighting&quot;: 2,
        ///    &quot;poison&quot;: 1,
        ///    &quot;ground&quot;: 1,
        ///    &quot;flying&quot;: 1,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefendingPokemonTypesGen2 {
            get {
                return ResourceManager.GetString("DefendingPokemonTypesGen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;-none-&quot;: {
        ///    &quot;normal&quot;: 1,
        ///    &quot;fire&quot;: 1,
        ///    &quot;water&quot;: 1,
        ///    &quot;electric&quot;: 1,
        ///    &quot;grass&quot;: 1,
        ///    &quot;ice&quot;: 1,
        ///    &quot;fighting&quot;: 1,
        ///    &quot;poison&quot;: 1,
        ///    &quot;ground&quot;: 1,
        ///    &quot;flying&quot;: 1,
        ///    &quot;psychic&quot;: 1,
        ///    &quot;bug&quot;: 1,
        ///    &quot;rock&quot;: 1,
        ///    &quot;ghost&quot;: 1,
        ///    &quot;dragon&quot;: 1,
        ///    &quot;dark&quot;: 1,
        ///    &quot;steel&quot;: 1,
        ///    &quot;fairy&quot;: 1
        ///  },
        ///  &quot;normal&quot;: {
        ///    &quot;normal&quot;: 1,
        ///    &quot;fire&quot;: 1,
        ///    &quot;water&quot;: 1,
        ///    &quot;electric&quot;: 1,
        ///    &quot;grass&quot;: 1,
        ///    &quot;ice&quot;: 1,
        ///    &quot;fighting&quot;: 2,
        ///    &quot;poison&quot;: 1,
        ///    &quot;ground&quot;: 1,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefendingPokemonTypesGen6 {
            get {
                return ResourceManager.GetString("DefendingPokemonTypesGen6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PITIcon {
            get {
                object obj = ResourceManager.GetObject("PITIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PokeBackground {
            get {
                object obj = ResourceManager.GetObject("PokeBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Bulbasaur,Grass,Poison
        ///2,Ivysaur,Grass,Poison
        ///3,Venusaur,Grass,Poison
        ///4,Charmander,Fire,
        ///5,Charmeleon,Fire,
        ///6,Charizard,Fire,Flying
        ///7,Squirtle,Water,
        ///8,Wartortle,Water,
        ///9,Blastoise,Water,
        ///10,Caterpie,Bug,
        ///11,Metapod,Bug,
        ///12,Butterfree,Bug,Flying
        ///13,Weedle,Bug,Poison
        ///14,Kakuna,Bug,Poison
        ///15,Beedrill,Bug,Poison
        ///16,Pidgey,Normal,Flying
        ///17,Pidgeotto,Normal,Flying
        ///18,Pidgeot,Normal,Flying
        ///19,Rattata,Normal,
        ///20,Raticate,Normal,
        ///21,Spearow,Normal,Flying
        ///22,Fearow,Normal,Flying
        ///23,Ekans,Pois [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pokedex {
            get {
                return ResourceManager.GetString("Pokedex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Bulbasaur,Grass,Poison
        ///2,Ivysaur,Grass,Poison
        ///3,Venusaur,Grass,Poison
        ///3.1,Venusaur (Mega),Grass,Poison
        ///4,Charmander,Fire,
        ///5,Charmeleon,Fire,
        ///6,Charizard,Fire,Flying
        ///6.1,Charizard (Mega X),Fire,Dragon
        ///6.2,Charizard (Mega Y),Fire,Flying
        ///7,Squirtle,Water,
        ///8,Wartortle,Water,
        ///9,Blastoise,Water,
        ///9.1,Blastoise (Mega),Water,
        ///10,Caterpie,Bug,
        ///11,Metapod,Bug,
        ///12,Butterfree,Bug,Flying
        ///13,Weedle,Bug,Poison
        ///14,Kakuna,Bug,Poison
        ///15,Beedrill,Bug,Poison
        ///15.1,Beedrill (Mega),Bug,Poison
        ///16,Pidgey,Normal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PokedexGen6 {
            get {
                return ResourceManager.GetString("PokedexGen6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PokemonLogo {
            get {
                object obj = ResourceManager.GetObject("PokemonLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
